using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using JetRx.Common.Attributes;

namespace JetRx.Entities
{
    public class device
    {

        public device()
        {
        }

        internal device(string key)
        {
            _deviceKey = key;
        }
        private string _deviceKey;
        public int id { get; set; }
        /// <summary>
        /// The Manufacturer's Unique Identifier assigned to the device.
        /// </summary>
        [MaxLength(75)]
        public string deviceidentifier { get; set; }

        [MaxLength(75)]
        public string devicename { get; set; }

        public string appdeviceKey {
            get { return _deviceKey;
        }
            private set
            {

            }
        }

        [MaxLength(20)]
        public string devicetype { get; set; }

        /// <summary>
        /// Device Phone Number. This Field is required, Badrequest(400) status will returned if not provided.
        /// </summary>
        
        [MaxLength(20)]
        public string phonenumber { get; set; }
        /// <summary>
        /// Temporary User details with auto generated password. Once the device is successfully registered,
        /// a temporary user account is created using the device phone number as the username and an autogenerated
        /// password which can be used to authenticate the user till the user registers. 
        /// User can login with either  phone number or email address  and password after registration
        /// </summary>
        [NotMapped]
        public user device_user { get; set; }

    }
}
